'use strict';
const $=s=>document.querySelector(s), NS='http://www.w3.org/2000/svg';
const meta={
 'qwen-27b':{name:'Qwen 3.8',logo:'qwen',color:'#8463da'},
 'gemma-31b':{name:'Gemma 4',logo:'gemma',color:'#6aa88e'},
 'deepseek-v4-flash':{name:'DeepSeek V4',logo:'deepseek',color:'#6faff5'},
 'mimo-v2.6-flash-mopd':{name:'MiMo V2.6',logo:'mimo',color:'#2464df'},
 'mistral-medium35-q4':{name:'Mistral 3.5',logo:'mistral',color:'#df9663'}
};
let release, activeModel='all', repoTurns='8', concurrency='4', loadMetric='throughput';
function el(tag,cls,parent,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;if(parent)parent.append(e);return e;}
function logo(name,parent){const i=el('img','',parent);i.src='/assets/logos/'+name+'.svg';i.alt=name+' logo';i.width=24;i.height=24;return i;}
function rowName(m,parent){const e=el('div','row-name',parent);logo(meta[m.id].logo,e);el('span','',e,meta[m.id].name);return e;}
function svgEl(tag,attrs,parent,text){const e=document.createElementNS(NS,tag);Object.entries(attrs||{}).forEach(([k,v])=>e.setAttribute(k,v));if(text!==undefined)e.textContent=text;if(parent)parent.append(e);return e;}
function svgCanvas(parent,w,h,label){parent.replaceChildren();return svgEl('svg',{viewBox:'0 0 '+w+' '+h,role:'img','aria-label':label},parent);}
function svgText(s,x,y,text,size=11,color='#788493',anchor='start'){return svgEl('text',{x,y,fill:color,'font-size':size,'font-family':'Manrope, sans-serif','text-anchor':anchor},s,text);}
function scaleCounts(){const values=[['models','retained configurations'],['cold_speed_runs','cold-speed repetitions'],['sustained_runs','sustained-generation runs'],['coding_cases','HumanEval cases'],['serving_requests','measured load requests']];const root=$('#study-scale');root.replaceChildren();values.forEach(([key,label])=>{const d=el('div','scale-item',root);el('strong','',d,String(release.study_counts[key]));el('span','',d,label);});}
function tuning(){const q=release.models.find(m=>m.id==='qwen-27b');const rows=[{name:'M5 Ultra',value:q.speed['200000'].decode.median,detail:'8-bit MLX · no speculation',color:'#1d61e7'},{name:'M3 Ultra',value:release.optimized_m3_reference.decode_tps,detail:'Optimized artifact · MTP + selective prefill',color:'#a095c7'}];const root=$('#tuning-chart');root.replaceChildren();rows.forEach(r=>{const row=el('div','tune-row',root),label=el('div','tune-label',row);logo('apple',label);el('span','',label,r.name);el('strong','',label,r.value.toFixed(2));const track=el('div','track',row);const bar=el('i','',track);bar.style.setProperty('--w',(r.value/50*100)+'%');bar.style.setProperty('--bar',r.color);el('small','',row,r.detail+' · tok/s');});}
function contextLegend(){const root=$('#context-legend');root.replaceChildren();release.models.forEach(m=>{const b=el('button','',root);b.type='button';logo(meta[m.id].logo,b);el('span','',b,meta[m.id].name);b.setAttribute('aria-pressed',String(activeModel==='all'||activeModel===m.id));b.addEventListener('click',()=>{activeModel=activeModel===m.id?'all':m.id;contextLegend();contextGraph();});});}
function contextGraph(){const s=svgCanvas($('#context-chart'),570,300,'Measured generation speed at8192,32768,131072 and200000 input tokens. Five-run medians.');const lengths=[8192,32768,131072,200000], x=n=>42+n/200000*472, y=v=>250-v/80*224;
 [0,20,40,60,80].forEach(v=>{svgEl('line',{x1:42,x2:525,y1:y(v),y2:y(v),stroke:'#e2e7ed','stroke-width':1},s);svgText(s,33,y(v)+4,v,10,'#8792a0','end');});
 lengths.forEach((n,i)=>{svgEl('line',{x1:x(n),x2:x(n),y1:26,y2:250,stroke:'#edf0f4'},s);svgText(s,x(n),271,['8K','32K','128K','200K'][i],11,'#6d7a8b','middle');});svgText(s,43,17,'tok/s',9);
 release.models.forEach(m=>{const selected=activeModel==='all'||activeModel===m.id, values=lengths.map(n=>m.speed[String(n)].decode.median);const path=values.map((v,i)=>(i?'L':'M')+x(lengths[i])+','+y(v)).join(' ');svgEl('path',{d:path,fill:'none',stroke:meta[m.id].color,'stroke-width':selected?3:1.5,opacity:selected?1:.16,'stroke-linecap':'round'},s);
 values.forEach((v,i)=>{const c=svgEl('circle',{cx:x(lengths[i]),cy:y(v),r:selected?4:2.5,fill:meta[m.id].color,opacity:selected?1:.2,tabindex:selected?0:-1},s);const stat=m.speed[String(lengths[i])].decode;svgEl('title',{},c,meta[m.id].name+' · '+lengths[i].toLocaleString()+' input · '+v.toFixed(2)+' tok/s · range '+stat.min.toFixed(2)+'–'+stat.max.toFixed(2));const show=()=>{$('#context-readout').textContent=meta[m.id].name+' · '+lengths[i].toLocaleString()+' input · '+v.toFixed(2)+' tok/s · observed '+stat.min.toFixed(2)+'–'+stat.max.toFixed(2)+' · n='+stat.n;};c.addEventListener('mouseenter',show);c.addEventListener('focus',show);});
 if(activeModel===m.id)svgText(s,525,y(values[3])+4,values[3].toFixed(2),11,meta[m.id].color);
 });}
function historical(){const root=$('#historical-profiles');root.replaceChildren();release.historical_models.forEach(m=>{const c=el('article','historical-card',root);logo('qwen',c);const copy=el('div','historical-copy',c);el('h4','',copy,m.id.startsWith('qwen3.6')?'Earlier Qwen 3.6 · 35B A3B':'Earlier Qwen 3.8 · Q4_K_M');el('p','',copy,m.id.startsWith('qwen3.6')?'4-bit MLX affine · 8-bit gates':'GGUF Q4_K_M · native runtime');el('p','',copy,'Historical comparison · 30 groups complete; later trials omitted');const n=el('div','historical-number',c,m.speed['200000'].decode.median.toFixed(2));el('span','',n,'tok/s at 200K · n=5');});}
function sustained(){const s=svgCanvas($('#sustained-chart'),770,260,'Three-repeat sustained generation medians and observed min–max ranges.');const x=v=>180+v/45*370;
 [0,10,20,30,40].forEach(v=>{svgEl('line',{x1:x(v),x2:x(v),y1:12,y2:219,stroke:'#e8ecf1'},s);svgText(s,x(v),241,v,11,'#8691a0','middle');});svgText(s,576,241,'tok/s',10);
 release.models.forEach((m,i)=>{const cy=35+i*43,r=m.sustained.decode,color=meta[m.id].color;svgEl('image',{href:'/assets/logos/'+meta[m.id].logo+'.svg',x:8,y:cy-11,width:24,height:24},s);svgText(s,42,cy+4,meta[m.id].name,13,'#263245');svgEl('line',{x1:x(r.min),x2:x(r.max),y1:cy,y2:cy,stroke:color,'stroke-width':3},s);[r.min,r.max].forEach(v=>svgEl('line',{x1:x(v),x2:x(v),y1:cy-5,y2:cy+5,stroke:color,'stroke-width':1.5},s));const dot=svgEl('circle',{cx:x(r.median),cy,r:5,fill:color},s);svgEl('title',{},dot,'Median '+r.median.toFixed(5)+'; observed range '+r.min.toFixed(5)+'–'+r.max.toFixed(5)+'; n='+r.n);svgText(s,635,cy+3,r.median.toFixed(2),19,'#1d3557','end');svgText(s,651,cy+3,r.min.toFixed(2)+'–'+r.max.toFixed(2),10,'#8a95a4');});}
function quality(){const root=$('#quality-cards');root.replaceChildren();[...release.quality_results].sort((a,b)=>b.human.passed-a.human.passed).forEach(q=>{const c=el('article','quality-card',root),name=el('div','quality-name',c);logo(meta[q.id].logo,name);el('span','',name,meta[q.id].name);const s=svgEl('svg',{viewBox:'0 0 100 100',role:'img','aria-label':q.human.passed+' of 164 HumanEval cases passed'},c);svgEl('circle',{cx:50,cy:50,r:41,fill:'none',stroke:'#edf0f4','stroke-width':7},s);const circumference=2*Math.PI*41,ratio=q.human.passed/q.human.completed;svgEl('circle',{cx:50,cy:50,r:41,fill:'none',stroke:meta[q.id].color,'stroke-width':7,'stroke-dasharray':circumference*ratio+' '+circumference,'stroke-linecap':'round',transform:'rotate(-90 50 50)'},s);svgText(s,50,57,(ratio*100).toFixed(1)+'%',21,'#24334b','middle');el('p','',c,q.human.passed+' / '+q.human.completed+' cases passed');});repo();matrix();}
function repo(){const root=$('#repo-results');root.replaceChildren();release.quality_results.forEach(q=>{const r=q.repo[repoTurns],row=el('div','repo-row',root);rowName(q,row);const dots=el('div','attempts',row);dots.setAttribute('aria-label','Grouped attempt counts');const passed=r.passed||0;for(const [cls,n] of [['pass',passed],['fail',r.completed-passed],['budget',r.budget_limited],['resource',r.resource_limited],['omit',r.owner_omitted]])for(let i=0;i<n;i++){const d=el('span','attempt-dot '+cls,dots);d.title=({pass:'Task passed',fail:'Completed task did not pass',budget:'Request budget limit; unscored',resource:'Resource limit; unscored',omit:'Explicit owner omission; unrun'})[cls];}
 const v=el('div','repo-value',row);if(r.completed){el('strong','',v,r.passed+' / '+r.completed);el('div','',v,'completed attempts passed');}else if(r.budget_limited)v.textContent=r.budget_limited+' request limits · unscored';else v.textContent=r.resource_limited+' resource limits · '+r.owner_omitted+' owner omission';});}
function matrix(){const root=$('#quality-matrix');root.replaceChildren();release.quality_results.forEach(q=>{const row=el('div','matrix-row',root);rowName(q,row);el('span','badge'+(q.retrieval.scored?'':' warn'),row,q.retrieval.scored?q.retrieval.passed+' / '+q.retrieval.completed:q.retrieval.attempted+' request limits');el('span','badge'+(q.structured.passed===q.structured.completed?'':' warn'),row,q.structured.passed+' / '+q.structured.completed);});}
function serving(){const root=$('#load-chart');root.replaceChildren();const max=loadMetric==='throughput'?45:200,key=loadMetric==='throughput'?'aggregate_output_tok_s':'latency_median_s';$('#load-unit').textContent=loadMetric==='throughput'?'tok/s · aggregate':'seconds · shorter is better';release.models.forEach(m=>{const r=m.serving[concurrency],row=el('div','bar-row',root);rowName(m,row);const track=el('div','track',row),bar=el('i','',track);bar.style.setProperty('--w',(r[key]/max*100)+'%');bar.style.setProperty('--bar',meta[m.id].color);const v=el('div','bar-value',row,r[key].toFixed(2));el('small','',v,loadMetric==='throughput'?'tok/s':'seconds');});const axis=el('div','bar-scale',root);[0,max/3,max*2/3,max].forEach(v=>el('span','',axis,String(Math.round(v))));}
function replay(){const root=$('#replay-chart');root.replaceChildren();release.models.forEach(m=>{const r=m.replay.full,c=el('div','replay-row',root),row=el('div','bar-row',c);rowName(m,row);const track=el('div','track',row),bar=el('i','',track);bar.style.setProperty('--w',(r.measured_duration_s/60/55*100)+'%');bar.style.setProperty('--bar',meta[m.id].color);const v=el('div','bar-value',row,(r.measured_duration_s/60).toFixed(1));el('small','',v,'minutes');const note=el('div','replay-note',c);el('span','',note,r.served+' / '+r.turns+' served');el('span','',note,r.short_output_warnings+' short-output warnings');});}
function bindControls(){document.querySelectorAll('#repo-controls button').forEach(b=>b.addEventListener('click',()=>{repoTurns=b.dataset.turns;document.querySelectorAll('#repo-controls button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));repo();}));document.querySelectorAll('#concurrency-controls button').forEach(b=>b.addEventListener('click',()=>{concurrency=b.dataset.concurrency;document.querySelectorAll('#concurrency-controls button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));serving();}));document.querySelectorAll('#metric-controls button').forEach(b=>b.addEventListener('click',()=>{loadMetric=b.dataset.metric;document.querySelectorAll('#metric-controls button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));serving();}));}
async function load(){try{const response=await fetch('/assets/showcase-data.json');if(!response.ok)throw Error('Unavailable');release=await response.json();if(release.models.length!==5||release.scope.required_remaining!==0)throw Error('Unexpected scope');scaleCounts();tuning();contextLegend();contextGraph();historical();sustained();quality();serving();replay();$('#load-error').hidden=true;}catch(error){$('#load-error').hidden=false;}}
const zoom=$('#zoom');document.querySelectorAll('.zoomable').forEach(b=>b.addEventListener('click',()=>{const source=b.querySelector('img');$('#zoom-image').src=b.dataset.image;$('#zoom-image').alt=source.alt;zoom.showModal();}));$('#close-zoom').addEventListener('click',()=>zoom.close());zoom.addEventListener('click',e=>{if(e.target===zoom)zoom.close();});$('#retry').addEventListener('click',load);bindControls();load();
